language: scala
scala:
- 2.11.7
- 2.10.5
script:
- sbt clean coverage test
jdk:
- oraclejdk8
sudo: false
env:
  global:
  - secure: rjKIQaSX2muGto8IjaO2IIKWhNnvypT4JWKYvLT6487Zj/r0axNYMK7pWYNECN6bTfD/T6OsARFozA1e1pnoBIKDJ4El1a15u6Lwp/ABOtz4h52Q+4Nx4eKh5G7QywKmwj7vlSdTDN3kUQNmVDDPwzeGYHF7t2MYzhaq1iWKtySMJ6SpUsj/Fq5RKYky7Ri+0dbw9ww/FgJehhnCtSK7zH+gRu/lKEmXexSaQw25rNZUxBIcagYD4AqUKVvInHi50tCsmO2bjcupT43aP6oKsTGb3AFMl/dJIM6wE79doFdnzRtUqiOyd/apcv8b1Rh0mwHnCZR2vbJCgXeVSyfjCn5JkIa92yT8q3BTj9XlcapVwvfQNLW+t7Z/w3CNdCf3/g0Ju0nfkhIEFhPfisJAHf/QY6rDARJuyV5VyPq2P5OQIHPwTUoUhcfVFJ3F7B7q8hrs1SAP9lGhPcW5+ShEIaXiWCRo8qUREGR9EtQgOSw2JFHFmLuBnxy/uvh0LCnv/XpraToZ6t7epPlDvJGaGjCQuDgCvFat/fnmIOg0axvGRY0O2fQARuTIOKDhF9APo4Z9JjBFD87Y9nwt7vWdteeSePOZTnrA/v4loX7xuPcp5eQ2KIrSg0tS2aFWZZpKwcbv0TmsbZnTapBqiQz4CwAU3azBs8+sErQbOfYQPzM=
  - secure: o1wg5ooGw29ifnrH6LzbUZ1HdAF6BW846ozTqS3KFRGbfb25XYIAxGkRMleldjOhkaVvsnwWTcbKZ8A4jTkrgVAQhM6nzzgDToME+BW6bIQZYdh4Vt1vvKQCICazkaygS5sqOKsxLR25sHxG4kZ000d4l4z/Um7naEOfoG/W8/cdPXxxGgGfCUVJRq7ECj2RxJ3+bRPB72bnJswHxdpCvyymuRzWdBpIPOCdZxMC9KZfK+Z5POAoRl7jPWUSGVRLxzFz8GdxuSH+g8kMEhMrgLvnc0ivSOtsPMVIKco6y5prfXa9n3EZqwTVWHXnkUnzzOcTeYWrD2XS4+AkD6URj9HZOlt9iApYT3F7oi8VEkhs4MNwpyhIqDbvcgzTcXa/lOYev1Zc08/neaefz26y9pwS+BpjqVTu1/5bunbQq313cTtzb22Eei0qTfXxFSd1I6qJKqirKA2gzQSLkBiSvcumRoMQi+QSKVJm5l9GIi/aRrwNShU/t6x4wcempdVBrdDpV19xYONE0Qpy3WgG5UHQcAEq+Cz7RgWkUknM/PD1/poLM6/cnyForth1Y5gGyWm32G4egHuzhc4gdB6hXiulwS6NFv+8gxgfau1+zNi62zEYikuuM2B9nc+mbOeokYab7kaC2h/h9zwnQUKu2LT0Pe7bplA8g0/MeZpCggU=
after_success:
  - sbt coveralls